package com.astoma.cs211e;

import java.rmi.RemoteException;

/**
 * Class creates table in Oracle on Hills server, populates table with values 
 * for the purpose of RMI programs testing.
 * cs211e HomeWork # 5 
 * @author Andrei Stoma
 * Mar 22, 2017
 */

import java.sql.*;
import java.util.Scanner;

public class FiftyStatesRMI
{
  private static ResultSet result;

  public static void main(String[] args) throws SQLException
  {
    DatabaseManager dbm = new DatabaseManager();
    dbm.getConnection();
    System.out.println("Connected to the database");

    dbm.execute(
	"create table fiftystates_astoma(id number generated by default on null as identity, state varchar2(20) not null, capital varchar2(20) not null)");
    System.out.println("Table with three fields has been created");

    // table with three fields created. Now populate
    FileManager fm = new FileManager("US_states");
    fm.map.forEach(
	(k, v) -> dbm.execute("insert into fiftystates_astoma (state, capital) values('" + k + "','" + v + "')"));
    
    try
    {
      AddServerImpl test = new AddServerImpl();
      String[] capitals = test.getCapitals("^S");
      System.out.println("Capitals:");
      for (int i = 0; i<capitals.length; i++)
      System.out.println(capitals[i]);
      
      String[] states = test.getStates("^S");
      System.out.println("States:");
      for (int i = 0; i<states.length; i++)
      System.out.println(states[i]);

      
    } catch (RemoteException e)
    {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    
    // drop the table
   //dbm.execute("drop table fiftystates_astoma");
    dbm.closeConnection();
   // System.out.println("Database connection has been closed");
  } // end main
} // end class
